name: Update WakaTime Stats

on:
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update WakaTime Readme Stats
        uses: athul/waka-readme@v1.2.2
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
